# Generated by Django 5.2.7 on 2025-10-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('cui', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('semestre', models.PositiveIntegerField()),
                ('peso_parcial_1', models.PositiveIntegerField()),
                ('peso_parcial_2', models.PositiveIntegerField()),
                ('peso_parcial_3', models.PositiveIntegerField()),
                ('peso_continua_1', models.PositiveIntegerField()),
                ('peso_continua_2', models.PositiveIntegerField()),
                ('peso_continua_3', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('cantidad_reservas', models.IntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoTeoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_teoria', to='siscad.curso')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_teoria', to='siscad.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('grupo_teoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_practica', to='siscad.grupoteoria')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_practica', to='siscad.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=1)),
                ('cupos', models.IntegerField()),
                ('grupo_teoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_laboratorio', to='siscad.grupoteoria')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_laboratorio', to='siscad.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Alta'), ('P', 'Promedio'), ('B', 'Baja')], max_length=1)),
                ('archivo', models.FileField(upload_to='archivos/Examenes')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='siscad.alumno')),
                ('GrupoTeoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='siscad.grupoteoria')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('T', 'Teoría'), ('P', 'Práctica'), ('L', 'Laboratorio'), ('R', 'Reserva')], max_length=1)),
                ('aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas', to='siscad.aula')),
                ('grupo_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siscad.grupolaboratorio')),
                ('grupo_practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siscad.grupopractica')),
                ('grupo_teoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siscad.grupoteoria')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta')], max_length=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='siscad.alumno')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_alumnos', to='siscad.hora')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_curso', to='siscad.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_curso', to='siscad.curso')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_laboratorio', to='siscad.alumno')),
                ('grupo_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_laboratorio', to='siscad.grupolaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Parcial'), ('C', 'Continua')], max_length=1)),
                ('periodo', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='siscad.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta')], max_length=1)),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_profesores', to='siscad.hora')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='siscad.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='siscad.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='siscad.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='hora',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='siscad.reserva'),
        ),
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='archivos/Silabos')),
                ('grupo_teoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silabos', to='siscad.grupoteoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('H', 'Hecho'), ('N', 'No hecho')], max_length=1)),
                ('fecha', models.DateField()),
                ('grupo_teoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='siscad.grupoteoria')),
                ('silabo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='siscad.silabo')),
            ],
        ),
    ]
