# Generated by Django 5.2.7 on 2025-10-22 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0002_administrador_user_alumno_user_profesor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='prerequisito_codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='turno',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='siscad.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='peso_continua_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='peso_continua_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='peso_continua_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='peso_parcial_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='peso_parcial_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='peso_parcial_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
