# Generated by Django 5.2.7 on 2025-10-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0003_curso_codigo_curso_prerequisito_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='tipo',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
