# Generated by Django 5.2.7 on 2025-10-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0004_aula_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
