# Generated by Django 5.2.7 on 2025-10-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0005_alter_nota_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='semestre_asignado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
