# Generated by Django 5.2.7 on 2025-10-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0006_alumno_semestre_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horas_laboratorio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_practica',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_teoria',
            field=models.IntegerField(default=0),
        ),
    ]
