# Generated by Django 5.2.7 on 2025-10-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0007_curso_horas_laboratorio_curso_horas_practica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='dia',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes')], max_length=1),
        ),
    ]
