# Generated by Django 5.2.7 on 2025-11-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0008_alter_hora_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='tipo',
            field=models.CharField(blank=True, choices=[('T', 'Teoría'), ('P', 'Práctica'), ('L', 'Laboratorio'), ('R', 'Reserva')], max_length=1, null=True),
        ),
    ]
