# Generated by Django 5.2.7 on 2025-11-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0010_reserva_aula_reserva_fecha_alter_reserva_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siscad.aula'),
        ),
    ]
