# Generated by Django 5.2.7 on 2025-11-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0011_alter_reserva_aula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaalumno',
            options={'ordering': ['fecha', 'hora', 'alumno']},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaalumno',
            unique_together={('alumno', 'fecha', 'hora')},
        ),
    ]
