# Generated by Django 5.2.7 on 2025-11-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0012_alter_asistenciaalumno_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaalumno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistenciaalumno',
            name='grupo_laboratorio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaalumno',
            name='tipo_clase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaalumno',
            name='turno_practica',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaalumno',
            name='turno_teoria',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaalumno',
            unique_together={('alumno', 'fecha', 'hora', 'tipo_clase', 'turno_teoria', 'turno_practica', 'grupo_laboratorio')},
        ),
    ]
