# Generated by Django 5.2.7 on 2025-11-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscad', '0013_alter_asistenciaalumno_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaalumno',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaalumno',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('P', 'Parcial'), ('C', 'Continua'), ('S', 'Sustitutorio')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='asistenciaalumno',
            name='grupo_laboratorio',
        ),
        migrations.RemoveField(
            model_name='asistenciaalumno',
            name='tipo_clase',
        ),
        migrations.RemoveField(
            model_name='asistenciaalumno',
            name='turno_practica',
        ),
        migrations.RemoveField(
            model_name='asistenciaalumno',
            name='turno_teoria',
        ),
    ]
