from .registrar_asistencia_alumnos import *
from .registrar_asistencia_profesores import *
from .visualizar_matriculados_admin import *
from .estadisticas_curso_admin import *
from .notas_alumnos_admin import *
from .reservas_aulas_admin import *
from .matricula_laboratorio_admin import *
from .ver_horarios_admin import *
from .reporte_asistencia_alumno_admin import *
from .ingresar_notas_admin import *
from .subir_silabo_admin import *
from .visualizar_avance_admin import *
from .listar_grupos_laboratorio_admin import *
from .visualizar_horario_alumno_admin import *
from .visualizar_horario_profesor_admin import *
